In [7]:
a = [[1,2,3],[4,5,6]] # python에서 제공하는 데이터 타입인 list
b = a

print(a is b)      # 같은 주소
print(a == b)

a[0][0] = 10
print(a is b)
print(a == b)


True
True
True
True


In [8]:
a = [[1,2,3],[4,5,6]] # python에서 제공하는 데이터 타입인 list
c = a.copy()
print(a is c)
print(a == c)

a[0][0] = 10
print(a is c)
print(a == c)

False
True
False
True


In [13]:
import copy
a = [[1,2,3],[4,5,6]] # python에서 제공하는 데이터 타입인 list
d = copy.deepcopy(a)
print(a is d)
print(a == d)

a[0][0] = 10
print(d[0] is a[0])
print(d[0] == a[0])

False
True
False
False


array는 homogeneous, sequence, mutable이다   
list는 hetergeneous, sequence, mutable이다

In [22]:
import numpy as np
a = b= np.array([1,2,3])
print(a is b)
print(a == b)

True
[ True  True  True]


In [23]:
a[0]

1

In [24]:
a[:]

array([1, 2, 3])

In [25]:
a[0] =100
print(a[0])
print(b[0])

100
100


In [26]:
a = np.array([1,2,3])
b= a.copy()         # numpy에서 제공되는 copy는 바로 deepcopy가 제공됨
print(a is b)
print(a == b)

False
[ True  True  True]


### as 계열
다른 데이터 타입을 가져와 바꿔서 사용할때는  as라는 이름이 보통 붙는다.

In [27]:
a = [1.5, 2.5, 3.5]
b= np.array(a)
print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [29]:
a = [1.5, 2.5, 3.5]
b= np.asarray(a)
print(type(a))
print(type(b))
print(type(a[0]))
print(type(b[0]))

<class 'list'>
<class 'numpy.ndarray'>
<class 'float'>
<class 'numpy.float64'>


In [30]:
a = [1,2,3]
b= np.asfarray(a)
print(type(a))
print(type(b))
print(type(a[0]))
print(type(b[0]))

<class 'list'>
<class 'numpy.ndarray'>
<class 'int'>
<class 'numpy.float64'>


### 값 가져오기

####(1) 인덱싱, 슬라이싱 방법 가능

In [38]:
a = [[1,2,3],[4,5,6]]  # python의 list
b = np.array(a)        # numpy의 array

In [33]:
print(a[0])
print(b[0])

[1, 2, 3]
[1 2 3]


In [34]:
print(type(a[0])) # list
print(type(b[0])) # numpy.array

<class 'list'>
<class 'numpy.ndarray'>


In [36]:
#print(a[0,1])  #list라 불가능
print(b[0,1])

2


In [41]:
print(a[slice(0,1)])  #0행부터 1행 미만 데이터를 가져온다
print(a[0])           # 1차원으로 가져온다

[[1, 2, 3]]
[1, 2, 3]


numpy는 기본적으로 인데깃ㅇ/슬라이싱 할때 comma를 사용할 수 있다

In [43]:
#numpy
print(type(b))
print(b[0,1])     # indexing[행, 열]
print(b[0][1])    # indexing[행][열]
print(b[0, -1])   # indexing
print(b[0:1,0:2]) # slicing
print(b[0:2,0:2]) # slicing

<class 'numpy.ndarray'>
2
2
3
[[1 2]]
[[1 2]
 [4 5]]


In [44]:
#pyhon
print(type(a))
print(a[0][1])    # indexing[행][열]
print(a[0:1]) # slicing
print(a[0:1][0:2]) # slicing


<class 'list'>
2
[[1, 2, 3]]
[[1, 2, 3]]


(2) boolean indexing

In [45]:
a = [[1,2,3,], [4,5,6]]
print(type(a))

<class 'list'>


In [47]:
print(type(a))
print(a*3)
a>3


<class 'list'>
[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


TypeError: ignored

In [49]:
b = np.array([[1,2,3,4]])
c = np.array([[2,2,2,2]])
b>c

array([[False, False,  True,  True]])

arrat은 scalar와 연산하면 elementwise로 계산한다
elementwise : 원소별로 각각 계산이 된다

In [56]:
p = np.array([[False, False,  True,  True]])
p

array([[False, False,  True,  True]])

In [54]:
b[np.array([[False, False,  True,  True]])]

array([3, 4])

In [57]:
b[b>2]

array([3, 4])

num에서 boolean indexing 조건
- array만 가능하다
- numpy TRue, False로만 가능하다
- shape가 맞아야한다(개수가 맞을때만 사용할 수 있다)


In [58]:
#파이썬에서는 boolean indexing을 지원 안한다
a = [[1,2,3,4]]
a = [[False,False,True,True]]

TypeError: ignored

(3) fancy indexing

In [59]:
b = np.arange(100)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [67]:
#np.arange([start]end[,step])
#reshape 재정립
b = np.arange(100).reshape(20,5)

#print(a.shape)
print(b.shape)
print(b )

(20, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


In [71]:
#print(b[:])     # 전체
#print(b[1,3])   # 8   b[행,열]   1행 3열 데이터를 가져온다
#print(b[1:3,2:4]) # 1행부터 3행미만 , 2열부터 4열 미만
print(b[[1,3,5],[0,2,4]]) #1행0열 3행 2열 5행4열 데이터
print(b[[1,3,5]])     # 1행 3생 5행 들고옴

print(b[:,[0,2,4]])

[ 5 17 29]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]]
[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]
 [25 27 29]
 [30 32 34]
 [35 37 39]
 [40 42 44]
 [45 47 49]
 [50 52 54]
 [55 57 59]
 [60 62 64]
 [65 67 69]
 [70 72 74]
 [75 77 79]
 [80 82 84]
 [85 87 89]
 [90 92 94]
 [95 97 99]]


In [72]:
# fancy index에서 주의사항
#print(b[[1,3,5],[0,2]])  # 행과 열의 갯수르 같게 지정해야 한다

print(b[:,[0,2,4]])       # fancy indexing에서는 slicing사용

IndexError: ignored

In [73]:
print(b[[1,3,4],[0]])  # broadcast으로 처리가 되어서 갯수가 다르지만 정상적으로 수행한다  행가져오기

[ 5 15 20]


In [74]:
print(b[[0,1,3,4],[0,1]])  # 이렇게 못쓴다는 의미

IndexError: ignored

In [111]:
m = np.array([[1,2],[3,4]])
n = np.array([[2,2]])
c = np.array([[2]])
d = np.array([[2],[2]])
print(m.shape)
print(n.shape)
print(c.shape)
print(d.shape)

(2, 2)
(1, 2)
(1, 1)
(2, 1)


In [78]:
m+n

array([[3, 4],
       [5, 6]])

### 3차원에서 이상에서 차원 구분법

In [81]:

b = np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [82]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
b[0][0]

array([0, 1, 2, 3])

In [88]:
b[1,1]

array([16, 17, 18, 19])

In [85]:
b[0,0]

array([0, 1, 2, 3])

In [86]:
b[0,0,0]

0

In [89]:
b[:,1,3]  # 모든공간 1행 3열 가져옴

array([ 7, 19])

In [95]:
m = np.arange(1,9).reshape(2,4)
n = np.array([[2,2]])

print(m)
print(n)


[[1 2 3 4]
 [5 6 7 8]]
[[2 2]]


In [94]:
m+n

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [96]:
m+n

ValueError: ignored

In [108]:
m = np.arange(1,9).reshape(2,4)
print(m.shape)
n = np.array([[2,4]])
print(n.shape)
n = np.array([[2]])
print(n.shape)

(2, 4)
(1, 2)
(1, 1)


In [ ]:
1 1 1 1
1 1 1 1

1 1

1

In [107]:
m = np.arange(1,9).reshape(1,4)
n = np.array([[2,4]])
m+n

ValueError: ignored

In [102]:
m = np.arange(1,9).reshape(1,4)
n = np.array([[2]])
m+n


ValueError: ignored

In [105]:
m = np.arange(1,9).reshape(2,4)
print(m.shape)
n = np.array([[2]])
print(n.shape)


(2, 4)
(1, 1)


In [106]:
m+n

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [120]:
a = np.array([2])
print(a.shape)
b = np.array([[2]])
print(b.shape)
c = np.array([[2],[2]])
print(c.shape)
d = np.array([[2,2]])
print(d.shape)
e = np.array([[2,2],[2,2]])
print(e.shape)

m = np.arange(1,9).reshape(2,4)
print(m.shape)


(1,)
(1, 1)
(2, 1)
(1, 2)
(2, 2)
(2, 4)


In [121]:
a+m

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [122]:
b+m

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [123]:
c+m

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [124]:
d+m

ValueError: ignored

In [125]:
e+m

ValueError: ignored

In [160]:
b = np.arange(24).reshape(2,3,4)

In [153]:
b = np.array([[[2]]])

In [161]:
b[:,1,3]  # 모든공간 1행 3얄

array([ 7, 19])

In [163]:
b[:,:,1] # 모든공간 모든행 1열

array([[ 1,  5,  9],
       [13, 17, 21]])

### fancy indexing 와 indexing 차이
- indexing은 원래 차원에서 하나 감소해서 가져오고 fancy indexing은 그대로 가져온다

In [162]:
b[0]  # = b[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [164]:
b[[0]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

Ellipsis
... (Ellipsis)는 이후로 모든것을 의미한다

In [170]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [165]:
b[0]  # = b[0,:,:]  = b[0,...]
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [166]:
# 숫자 1, 5,9 만 가져온다

b[0,:,1]

array([1, 5, 9])

In [167]:
# 숫자 1,5,9,3,7,11
b[:,1,:]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [169]:
b[:,1:2,:]

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

In [174]:
b[:,:,3:4,]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [175]:
b[...,3]

array([[ 3,  7, 11],
       [15, 19, 23]])

## 줄임표현(...)
출력해야할 데이터 수가 엄청 클때 보이는 ..은 ellipsis와 다르다

In [176]:
# out에 나오는 ...은 단순히 줄임표현이다

In [177]:
np.set_printoptions(edgeitems=6)

In [178]:
np.arange(10000)

array([   0,    1,    2,    3,    4,    5, ..., 9994, 9995, 9996, 9997,
       9998, 9999])

## 연산
numpy 연산의 기본은 두 개의 shape이 같앙 한다

In [181]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [185]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [186]:
# 같은 위치의 원소끼리 더해준다
a + b

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [187]:
#python의 lsit에서 +연산잔s elementwise가 아니라 list를 화장시킨다
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [188]:
@np.vectorize
def plus(a,b):
  return a+b

plus([1,2,3],[4,5,6])

array([5, 7, 9])

In [191]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [192]:
b = np.arange(6,12).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [193]:
a*b

array([[ 0,  7, 16],
       [27, 40, 55]])

In [194]:
#python에서 list끼리 곱하기를 할수 없다
[1,2,3]*[4,5,6]

TypeError: ignored

In [196]:
c = np.matrix([[1,2],[3,4]])   # 행렬 생성
c

matrix([[1, 2],
        [3, 4]])

In [197]:
c*c               #행렬 곱은 * 가아니라 파이썬에썬 @ 로한다
# 1*1 +2*3     1*2+2*4
# 3*1+4*3      3*2+4*4

matrix([[ 7, 10],
        [15, 22]])

ndarrat에서 행렬곱 연산자 @이다

In [198]:
a@b  #행렬 사이즈가 안맞아서 안되는거

ValueError: ignored

행렬곱을 하기 위해서는 shape가 맞아야 한다
T는 transpose(전치)의 약자이다

In [200]:
a = np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [201]:
print(a.T)  #T는 뒤집는거

[[0 3]
 [1 4]
 [2 5]]


In [202]:
a@a.T

array([[ 5, 14],
       [14, 50]])

In [211]:
a = np.arange(1,17).reshape(1,16)

In [212]:
a@a.T

array([[1496]])

matrix는 *와@ 모두가 가능하다

함수방법으로 np.dot()을 사용할 수 있다.

In [213]:
np.dot(a,a.T)  # = a@a.T

array([[1496]])

* : matrix   
@ : matrix ,ndarray   
dot() : matrix ,ndarray    

method 방식으로 행렬곱 할수 있다    
function 방법과 사용하는 법이 다르므로 주의한다

In [214]:
np.dot(c,c.T)  #함수방식

matrix([[ 5, 11],
        [11, 25]])

In [215]:
 c.dot(c,c.T)  # 메소드 방식

ValueError: ignored

##strides
strides는 다음 원소끼릴의 메모리 크기를 차원별로 알려준다   
c의 포인터 개념을 알고있으면 이해하기가 쉽다

In [217]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [218]:
#행의 메모리 간격은 32byte
#열의 메모리 간격은 8byte
a.strides

(32, 8)

In [220]:
a.dtype

dtype('int64')

In [ ]:
#열의 원소갯수 * itemsize = 행의 메모리간격
# itemsize = 열의 메모리 간격

##axis
axis는 다차월 배열을 연산할때 기준이 되는 축이다

In [221]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [222]:
np.sum(a)

66

In [224]:
np.sum(a, axis=0) # 행기준 - 인데 열기준

array([12, 15, 18, 21])

(0.0) (0.1) (0.2) (0.3)
(1.0) (1.1) (1.2) (1.3)
(2.0) (2.1) (2.2) (2.3)

In [225]:
np.sum(a, axis=1) #열기준 -인데 행기준

array([ 6, 22, 38])

In [227]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [228]:
np.sum(a)  #(2,3,4) -> (1,)

276

In [229]:
np.sum(a,axis=0) #(2,3,4) -> (3,4)  3행,4렬

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [230]:
np.sum(a,axis=1)   #(2,3,4) -> (2,4)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [231]:
np.sum(a,axis=2)   #(2,3,4) -> (2,3)

array([[ 6, 22, 38],
       [54, 70, 86]])

###array모양바꾸기
(1)reshape
reshape는 차원을 바꿔즈는 기능을 한다

In [236]:
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [239]:
b = a.reshape(3,8)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [245]:
#b=a.reshape(2,3,5)  # 크기가 맞지 않음
b=a.reshape(2,3,-1)  #알아서 채워짐
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [246]:
b=a.reshape(2,3,-100)  #알아서 채워짐   # 그래도 계산불가능하면 안된다
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [252]:
b = a.reshape(3,4,2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [248]:
np.sum(b,axis=0) #(3,4,2) -> (4,2)  3행,4렬

array([[24, 27],
       [30, 33],
       [36, 39],
       [42, 45]])

In [249]:
np.sum(b,axis=1) #(3,4,2) -> (3,2)  3행,4렬

array([[12, 16],
       [44, 48],
       [76, 80]])

In [250]:
np.sum(b,axis=2) #(3,4,2) -> (3,4)  3행,4렬

array([[ 1,  5,  9, 13],
       [17, 21, 25, 29],
       [33, 37, 41, 45]])